-- Unsubscribe feedback.
-- The unsubscribe page (docs/unsubscribe.html, generated by generate_site.py)
-- collects an optional reason and calls save_unsub_reason(t, reason) BEFORE the
-- existing unsubscribe(t) RPC. Only the reason is stored - no email/name/PII -
-- so it stays consistent with the privacy policy ("we keep subscriber details
-- only while you remain subscribed").
--
-- Run once in the Supabase SQL editor (or: supabase db execute).

create table if not exists public.unsub_reasons (
  id         bigint generated always as identity primary key,
  reason     text not null,
  created_at timestamptz not null default now()
);

-- Anon/authenticated reach this only through the SECURITY DEFINER RPC below,
-- never the table directly.
revoke all on public.unsub_reasons from anon, authenticated;

create or replace function public.save_unsub_reason(t text, reason text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Record a reason only for a token that matches a real subscriber, so the
  -- endpoint can't be used to insert arbitrary rows.
  if t is not null and exists (select 1 from public.inquiries where unsub_token = t) then
    insert into public.unsub_reasons(reason) values (left(coalesce(reason, ''), 200));
  end if;
end;
$$;

grant execute on function public.save_unsub_reason(text, text) to anon, authenticated;
